/** @type {import('tailwindcss').Config} */

import daisyui from 'daisyui';

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      boxShadow: {
        glow: "0 18px 60px rgba(132, 62, 39, 0.18)",
        soft: "0 10px 30px rgba(45, 33, 22, 0.12)",
      },
      fontFamily: {
        display: ['"Fraunces"', "Georgia", "serif"],
        sans: ['"Manrope"', "ui-sans-serif", "system-ui", "sans-serif"],
      },
      keyframes: {
        floaty: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
        rise: {
          from: { opacity: "0", transform: "translateY(18px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        floaty: "floaty 6s ease-in-out infinite",
        rise: "rise 500ms ease-out both",
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        streamify_daybreak: {
          primary: "#B85C38",
          "primary-content": "#FFF8F0",
          secondary: "#2F6F63",
          "secondary-content": "#F4F8F6",
          accent: "#E1A95F",
          "accent-content": "#2D241A",
          neutral: "#2D241A",
          "neutral-content": "#FFF7EE",
          "base-100": "#F8F1E8",
          "base-200": "#F2E6D9",
          "base-300": "#E5D3BF",
          "base-content": "#2D241A",
          info: "#4B89A8",
          success: "#2F7A63",
          warning: "#C67A28",
          error: "#B24634",
          "--rounded-box": "1.6rem",
          "--rounded-btn": "999px",
          "--rounded-badge": "999px",
          "--animation-btn": "0.2s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.98",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "1rem",
        },
      },
      {
        streamify_midnight: {
          primary: "#E58B62",
          "primary-content": "#21150F",
          secondary: "#7BC3B5",
          "secondary-content": "#10211D",
          accent: "#F1C37A",
          "accent-content": "#241B0E",
          neutral: "#F3E7D7",
          "neutral-content": "#16110D",
          "base-100": "#1B1613",
          "base-200": "#241D19",
          "base-300": "#302722",
          "base-content": "#F5EBDD",
          info: "#7CB5D1",
          success: "#73C6AB",
          warning: "#F2B96A",
          error: "#E47A68",
          "--rounded-box": "1.6rem",
          "--rounded-btn": "999px",
          "--rounded-badge": "999px",
          "--animation-btn": "0.2s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.98",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "1rem",
        },
      },
      {
        streamify_olive: {
          primary: "#7C6A3B",
          "primary-content": "#FBF7ED",
          secondary: "#4B6A49",
          "secondary-content": "#F1F7F0",
          accent: "#D29D48",
          "accent-content": "#2B2417",
          neutral: "#2B261C",
          "neutral-content": "#FBF6EA",
          "base-100": "#F4EFE5",
          "base-200": "#ECE2D2",
          "base-300": "#D9CCB5",
          "base-content": "#2B261C",
          info: "#4D8191",
          success: "#4E7756",
          warning: "#C78B36",
          error: "#B1533D",
          "--rounded-box": "1.6rem",
          "--rounded-btn": "999px",
          "--rounded-badge": "999px",
          "--animation-btn": "0.2s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.98",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "1rem",
        },
      },
      {
        streamify_tide: {
          primary: "#3E7C87",
          "primary-content": "#EEF6F7",
          secondary: "#76A692",
          "secondary-content": "#12231E",
          accent: "#D8A255",
          "accent-content": "#302012",
          neutral: "#21363B",
          "neutral-content": "#F1F7F7",
          "base-100": "#EEF4F4",
          "base-200": "#E0EAEA",
          "base-300": "#C6D5D5",
          "base-content": "#21363B",
          info: "#4F93B5",
          success: "#5A9B80",
          warning: "#C98A3D",
          error: "#B55D52",
          "--rounded-box": "1.6rem",
          "--rounded-btn": "999px",
          "--rounded-badge": "999px",
          "--animation-btn": "0.2s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.98",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "1rem",
        },
      },
      {
        streamify_ember: {
          primary: "#C96C4A",
          "primary-content": "#201311",
          secondary: "#8A6C8F",
          "secondary-content": "#F8F0F8",
          accent: "#E0A35C",
          "accent-content": "#2D1E11",
          neutral: "#F6E9DE",
          "neutral-content": "#26161A",
          "base-100": "#21171A",
          "base-200": "#2B1E22",
          "base-300": "#39282E",
          "base-content": "#F6E9DE",
          info: "#78A8C8",
          success: "#6AB091",
          warning: "#E5AE63",
          error: "#E37C66",
          "--rounded-box": "1.6rem",
          "--rounded-btn": "999px",
          "--rounded-badge": "999px",
          "--animation-btn": "0.2s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.98",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "1rem",
        },
      },
      {
        streamify_bloom: {
          primary: "#B85F74",
          "primary-content": "#FFF5F7",
          secondary: "#5F816E",
          "secondary-content": "#F4F8F5",
          accent: "#D89A62",
          "accent-content": "#2F2118",
          neutral: "#33242A",
          "neutral-content": "#FFF6F7",
          "base-100": "#FBF1F1",
          "base-200": "#F3E4E4",
          "base-300": "#E4CDCF",
          "base-content": "#33242A",
          info: "#6A96BA",
          success: "#5F8E73",
          warning: "#D38A4C",
          error: "#B94D59",
          "--rounded-box": "1.6rem",
          "--rounded-btn": "999px",
          "--rounded-badge": "999px",
          "--animation-btn": "0.2s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.98",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "1rem",
        },
      },
    ],
  },
}
